
import { ClassLevel, Subject } from './types';

export const INITIAL_SUBJECTS: Record<ClassLevel, Subject[]> = {
  [ClassLevel.ONE]: [
    { id: 'bn', name: 'বাংলা', fullMarks: 100, passMarks: 33 },
    { id: 'en', name: 'English', fullMarks: 100, passMarks: 33 },
    { id: 'math', name: 'প্রাথমিক গণিত', fullMarks: 100, passMarks: 33 },
  ],
  [ClassLevel.TWO]: [
    { id: 'bn', name: 'বাংলা', fullMarks: 100, passMarks: 33 },
    { id: 'en', name: 'English', fullMarks: 100, passMarks: 33 },
    { id: 'math', name: 'প্রাথমিক গণিত', fullMarks: 100, passMarks: 33 },
  ],
  [ClassLevel.THREE]: [
    { id: 'bn', name: 'বাংলা', fullMarks: 100, passMarks: 33 },
    { id: 'en', name: 'English', fullMarks: 100, passMarks: 33 },
    { id: 'math', name: 'প্রাথমিক গণিত', fullMarks: 100, passMarks: 33 },
    { id: 'sci', name: 'প্রাথমিক বিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'bgs', name: 'বাংলাদেশ ও বিশ্ব পরিচয়', fullMarks: 100, passMarks: 33 },
    { id: 'rel', name: 'ধর্ম শিক্ষা', fullMarks: 100, passMarks: 33 },
  ],
  [ClassLevel.FOUR]: [
    { id: 'bn', name: 'বাংলা', fullMarks: 100, passMarks: 33 },
    { id: 'en', name: 'English', fullMarks: 100, passMarks: 33 },
    { id: 'math', name: 'প্রাথমিক গণিত', fullMarks: 100, passMarks: 33 },
    { id: 'sci', name: 'প্রাথমিক বিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'bgs', name: 'বাংলাদেশ ও বিশ্ব পরিচয়', fullMarks: 100, passMarks: 33 },
    { id: 'rel', name: 'ধর্ম শিক্ষা', fullMarks: 100, passMarks: 33 },
  ],
  [ClassLevel.FIVE]: [
    { id: 'bn', name: 'বাংলা', fullMarks: 100, passMarks: 33 },
    { id: 'en', name: 'English', fullMarks: 100, passMarks: 33 },
    { id: 'math', name: 'প্রাথমিক গণিত', fullMarks: 100, passMarks: 33 },
    { id: 'sci', name: 'প্রাথমিক বিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'bgs', name: 'বাংলাদেশ ও বিশ্ব পরিচয়', fullMarks: 100, passMarks: 33 },
    { id: 'rel', name: 'ধর্ম শিক্ষা', fullMarks: 100, passMarks: 33 },
  ],
  [ClassLevel.SIX]: [
    { id: 'bn1', name: 'বাংলা ১ম', fullMarks: 100, passMarks: 33 },
    { id: 'bn2', name: 'বাংলা ২য়', fullMarks: 100, passMarks: 33 },
    { id: 'en1', name: 'English 1st', fullMarks: 100, passMarks: 33 },
    { id: 'en2', name: 'English 2nd', fullMarks: 100, passMarks: 33 },
    { id: 'math', name: 'গণিত', fullMarks: 100, passMarks: 33 },
    { id: 'sci', name: 'বিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'bgs', name: 'বাংলাদেশ ও বিশ্ব পরিচয়', fullMarks: 100, passMarks: 33 },
    { id: 'ict', name: 'তথ্য ও যোগাযোগ প্রযুক্তি', fullMarks: 50, passMarks: 17 },
    { id: 'agri', name: 'কৃষি শিক্ষা', fullMarks: 100, passMarks: 33 },
    { id: 'rel', name: 'ধর্ম শিক্ষা', fullMarks: 100, passMarks: 33 },
  ],
  [ClassLevel.SEVEN]: [
    { id: 'bn1', name: 'বাংলা ১ম', fullMarks: 100, passMarks: 33 },
    { id: 'bn2', name: 'বাংলা ২য়', fullMarks: 100, passMarks: 33 },
    { id: 'en1', name: 'English 1st', fullMarks: 100, passMarks: 33 },
    { id: 'en2', name: 'English 2nd', fullMarks: 100, passMarks: 33 },
    { id: 'math', name: 'গণিত', fullMarks: 100, passMarks: 33 },
    { id: 'sci', name: 'বিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'bgs', name: 'বাংলাদেশ ও বিশ্ব পরিচয়', fullMarks: 100, passMarks: 33 },
    { id: 'ict', name: 'তথ্য ও যোগাযোগ প্রযুক্তি', fullMarks: 50, passMarks: 17 },
    { id: 'agri', name: 'কৃষি শিক্ষা', fullMarks: 100, passMarks: 33 },
    { id: 'rel', name: 'ধর্ম শিক্ষা', fullMarks: 100, passMarks: 33 },
  ],
  [ClassLevel.EIGHT]: [
    { id: 'bn1', name: 'বাংলা ১ম', fullMarks: 100, passMarks: 33 },
    { id: 'bn2', name: 'বাংলা ২য়', fullMarks: 100, passMarks: 33 },
    { id: 'en1', name: 'English 1st', fullMarks: 100, passMarks: 33 },
    { id: 'en2', name: 'English 2nd', fullMarks: 100, passMarks: 33 },
    { id: 'math', name: 'গণিত', fullMarks: 100, passMarks: 33 },
    { id: 'sci', name: 'বিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'bgs', name: 'বাংলাদেশ ও বিশ্ব পরিচয়', fullMarks: 100, passMarks: 33 },
    { id: 'ict', name: 'তথ্য ও যোগাযোগ প্রযুক্তি', fullMarks: 50, passMarks: 17 },
    { id: 'agri', name: 'কৃষি শিক্ষা', fullMarks: 100, passMarks: 33 },
    { id: 'rel', name: 'ধর্ম শিক্ষা', fullMarks: 100, passMarks: 33 },
  ],
  [ClassLevel.NINE]: [
    { id: 'bn1', name: 'বাংলা ১ম', fullMarks: 100, passMarks: 33 },
    { id: 'bn2', name: 'বাংলা ২য়', fullMarks: 100, passMarks: 33 },
    { id: 'en1', name: 'English 1st', fullMarks: 100, passMarks: 33 },
    { id: 'en2', name: 'English 2nd', fullMarks: 100, passMarks: 33 },
    { id: 'math', name: 'গণিত', fullMarks: 100, passMarks: 33 },
    { id: 'ict', name: 'তথ্য ও যোগাযোগ প্রযুক্তি', fullMarks: 50, passMarks: 17 },
    { id: 'phy', name: 'পদার্থবিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'chem', name: 'রসায়ন', fullMarks: 100, passMarks: 33 },
    { id: 'bio', name: 'জীববিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'bgs', name: 'বাংলাদেশ ও বিশ্ব পরিচয়', fullMarks: 100, passMarks: 33 },
    { id: 'hmath', name: 'উচ্চতর গণিত', fullMarks: 100, passMarks: 33 },
    { id: 'gsci', name: 'বিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'geo', name: 'ভূগোল ও পরিবেশ', fullMarks: 100, passMarks: 33 },
    { id: 'civic', name: 'পৌরনীতি ও নাগরিকতা', fullMarks: 100, passMarks: 33 },
    { id: 'hist', name: 'ইতিহাস ও বিশ্বসভ্যতা', fullMarks: 100, passMarks: 33 },
    { id: 'agri', name: 'কৃষি শিক্ষা', fullMarks: 100, passMarks: 33 },
    { id: 'rel', name: 'ধর্ম শিক্ষা', fullMarks: 100, passMarks: 33 },
  ],
  [ClassLevel.TEN]: [
    { id: 'bn1', name: 'বাংলা ১ম', fullMarks: 100, passMarks: 33 },
    { id: 'bn2', name: 'বাংলা ২য়', fullMarks: 100, passMarks: 33 },
    { id: 'en1', name: 'English 1st', fullMarks: 100, passMarks: 33 },
    { id: 'en2', name: 'English 2nd', fullMarks: 100, passMarks: 33 },
    { id: 'math', name: 'গণিত', fullMarks: 100, passMarks: 33 },
    { id: 'ict', name: 'তথ্য ও যোগাযোগ প্রযুক্তি', fullMarks: 50, passMarks: 17 },
    { id: 'phy', name: 'পদার্থবিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'chem', name: 'রসায়ন', fullMarks: 100, passMarks: 33 },
    { id: 'bio', name: 'জীববিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'bgs', name: 'বাংলাদেশ ও বিশ্ব পরিচয়', fullMarks: 100, passMarks: 33 },
    { id: 'hmath', name: 'উচ্চতর গণিত', fullMarks: 100, passMarks: 33 },
    { id: 'gsci', name: 'বিজ্ঞান', fullMarks: 100, passMarks: 33 },
    { id: 'geo', name: 'ভূগোল ও পরিবেশ', fullMarks: 100, passMarks: 33 },
    { id: 'civic', name: 'পৌরনীতি ও নাগরিকতা', fullMarks: 100, passMarks: 33 },
    { id: 'hist', name: 'ইতিহাস ও বিশ্বসভ্যতা', fullMarks: 100, passMarks: 33 },
    { id: 'agri', name: 'কৃষি শিক্ষা', fullMarks: 100, passMarks: 33 },
    { id: 'rel', name: 'ধর্ম শিক্ষা', fullMarks: 100, passMarks: 33 },
  ],
};
